import { useState } from "react";
import { FileUp, Plus, Send } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "./ui/button";

const labels: Record<string, string> = { submitted: "Recibida", under_review: "En revisión", approved: "Aprobada", rejected: "Rechazada", enrolled: "Matriculada", draft: "Borrador" };

export default function ApplicantAdmissionsPanel() {
  const [programName, setProgramName] = useState("");
  const [selected, setSelected] = useState<number | null>(null);
  const [documentType, setDocumentType] = useState("Documento de identidad");
  const applications = trpc.admissions.myApplications.useQuery();
  const create = trpc.admissions.createApplication.useMutation({ onSuccess: async () => { toast.success("Prematrícula enviada."); setProgramName(""); await applications.refetch(); }, onError: error => toast.error(error.message) });
  const upload = trpc.admissions.uploadDocument.useMutation({ onSuccess: async () => { toast.success("Documento cargado para revisión."); }, onError: error => toast.error(error.message) });
  const uploadFile = (file: File) => { if (!selected) return; if (file.size > 8 * 1024 * 1024) { toast.error("El archivo no puede superar 8 MB."); return; } const reader = new FileReader(); reader.onload = () => { const base64 = String(reader.result || "").split(",")[1]; if (base64) upload.mutate({ applicationId: selected, documentType, fileName: file.name, mimeType: file.type, base64 }); }; reader.readAsDataURL(file); };
  return <div className="space-y-6"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#B69A5E]/15 text-[#D8BF86]"><Send className="h-5 w-5" /></div><div><h2 className="font-display text-2xl font-bold text-white">Mi admisión</h2><p className="text-sm text-[#9AA8B9]">Solicita tu prematrícula y entrega los documentos requeridos.</p></div></div><section className="wij-card p-5"><h3 className="font-display text-lg font-bold text-white">Nueva prematrícula</h3><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input className="wij-input flex-1" placeholder="Programa o curso de interés" value={programName} onChange={event => setProgramName(event.target.value)} /><Button className="bg-[#B69A5E] text-[#171A17] hover:bg-[#D8BF86]" disabled={create.isPending || programName.trim().length < 2} onClick={() => create.mutate({ programName: programName.trim() })}><Plus className="h-4 w-4" />Enviar solicitud</Button></div></section><section className="space-y-3">{applications.isLoading ? <div className="wij-card p-8 text-center text-sm text-[#9AA8B9]">Cargando tus solicitudes…</div> : !applications.data?.length ? <div className="wij-card p-8 text-center text-sm text-[#9AA8B9]">Todavía no tienes solicitudes de admisión.</div> : applications.data.map(application => <article key={application.id} className="wij-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-display font-bold text-white">{application.programName}</h3><p className="mt-1 text-xs text-[#9AA8B9]">Solicitud #{application.id}</p></div><span className="rounded-full bg-[#B69A5E]/15 px-3 py-1 text-xs font-bold text-[#D8BF86]">{labels[application.status] || application.status}</span></div><div className="mt-4 flex flex-wrap items-center gap-3"><select className="wij-input max-w-xs" value={selected === application.id ? documentType : "Documento de identidad"} onChange={event => { setSelected(application.id); setDocumentType(event.target.value); }}><option>Documento de identidad</option><option>Certificado de estudios</option><option>Foto</option><option>Otro soporte</option></select><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-[#2F9E72] px-3 py-2 text-sm font-semibold text-white hover:bg-[#267F5C]"><FileUp className="h-4 w-4" />Cargar documento<input type="file" className="hidden" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={upload.isPending} onChange={event => { const file = event.target.files?.[0]; if (file) { setSelected(application.id); uploadFile(file); } }} /></label></div></article>)}</section></div>;
}
