import { BookOpen, Bot, MessageSquare, Plus, Send, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "./ui/button";

type Subject = { id: number; code: string; name: string; period: string };

export default function LearningHub({ subjects, isStaff }: { subjects: Subject[]; isStaff: boolean }) {
  const [section, setSection] = useState<"curriculum" | "ai" | "messages">("curriculum");
  const [subjectId, setSubjectId] = useState<number | null>(null);
  const [topic, setTopic] = useState("");
  const [level, setLevel] = useState<"basic" | "intermediate" | "advanced">("intermediate");
  const [period, setPeriod] = useState("2026-1");
  const [proposal, setProposal] = useState<any>(null);
  const [recipientId, setRecipientId] = useState("");
  const [message, setMessage] = useState("");
  const utils = trpc.useUtils();
  const activeSubjectId = subjectId ?? subjects[0]?.id ?? 0;
  const resources = trpc.academic.curriculum.resources.useQuery({ subjectId: activeSubjectId || 1 }, { enabled: Boolean(activeSubjectId) });
  const competencies = trpc.academic.curriculum.competencies.useQuery({ subjectId: activeSubjectId || 1 }, { enabled: Boolean(activeSubjectId) });
  const recipients = trpc.academic.messages.recipients.useQuery({ subjectId: activeSubjectId || 1 }, { enabled: Boolean(activeSubjectId) });
  const messages = trpc.academic.messages.list.useQuery({ subjectId: activeSubjectId || 1 }, { enabled: Boolean(activeSubjectId) });
  const generate = trpc.academic.ai.generateCourse.useMutation({ onSuccess: value => { setProposal(value); toast.success("Propuesta generada por IA."); }, onError: error => toast.error(error.message) });
  const createResource = trpc.academic.curriculum.addResource.useMutation({ onSuccess: () => { utils.academic.curriculum.resources.invalidate(); toast.success("Recurso agregado."); }, onError: error => toast.error(error.message) });
  const createCompetency = trpc.academic.curriculum.addCompetency.useMutation({ onSuccess: () => { utils.academic.curriculum.competencies.invalidate(); toast.success("Competencia agregada."); }, onError: error => toast.error(error.message) });
  const sendMessage = trpc.academic.messages.send.useMutation({ onSuccess: () => { setMessage(""); utils.academic.messages.list.invalidate(); toast.success("Mensaje enviado."); }, onError: error => toast.error(error.message) });
  const subjectLabel = useMemo(() => subjects.find(subject => subject.id === activeSubjectId), [subjects, activeSubjectId]);

  if (!subjects.length) return <div className="wij-card p-8 text-center"><BookOpen className="mx-auto h-8 w-8 text-[#75A7FF]" /><h2 className="mt-3 font-display text-lg font-bold text-white">Aún no tienes materias</h2><p className="mt-2 text-sm text-[#8898AA]">Cuando te asignen una materia, podrás ver sus recursos, competencias y conversaciones aquí.</p></div>;

  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-bold text-white">Centro de aprendizaje</h2><p className="mt-1 text-sm text-[#8898AA]">Recursos, competencias, IA y comunicación académica.</p></div><select className="wij-input max-w-xs" value={activeSubjectId} onChange={event => setSubjectId(Number(event.target.value))}>{subjects.map(subject => <option key={subject.id} value={subject.id}>{subject.code} · {subject.name}</option>)}</select></div><div className="flex flex-wrap gap-2"><Button size="sm" variant={section === "curriculum" ? "default" : "outline"} onClick={() => setSection("curriculum")}><BookOpen className="h-4 w-4" />Currículo</Button>{isStaff && <Button size="sm" variant={section === "ai" ? "default" : "outline"} onClick={() => setSection("ai")}><Sparkles className="h-4 w-4" />Generador IA</Button>}<Button size="sm" variant={section === "messages" ? "default" : "outline"} onClick={() => setSection("messages")}><MessageSquare className="h-4 w-4" />Mensajes</Button></div>
    {section === "curriculum" && <div className="grid gap-5 lg:grid-cols-2"><section className="wij-card p-5"><h3 className="font-display font-bold text-white">Competencias · {subjectLabel?.name}</h3><div className="mt-4 space-y-3">{competencies.data?.length ? competencies.data.map(item => <div key={item.id} className="rounded-xl border border-[#243356] bg-[#162040] p-3"><p className="font-semibold text-white">{item.title}</p><p className="mt-1 text-sm text-[#8898AA]">{item.description}</p><span className="mt-2 inline-block rounded-full bg-[#7C3AED]/15 px-2 py-1 text-[10px] font-bold uppercase text-[#B59AFF]">{item.level}</span></div>) : <p className="py-6 text-center text-sm text-[#8898AA]">No hay competencias registradas.</p>}</div>{isStaff && <Button className="mt-4 w-full" variant="outline" onClick={() => { const title = window.prompt("Nombre de la competencia"); if (title) createCompetency.mutate({ subjectId: activeSubjectId, data: { title, description: null, level: "intermediate" } }); }}><Plus className="h-4 w-4" />Agregar competencia</Button>}</section><section className="wij-card p-5"><h3 className="font-display font-bold text-white">Recursos de aprendizaje</h3><div className="mt-4 space-y-3">{resources.data?.length ? resources.data.map(item => <div key={item.id} className="rounded-xl border border-[#243356] bg-[#162040] p-3"><p className="font-semibold text-white">{item.title}</p><p className="mt-1 text-sm text-[#8898AA]">{item.description || "Material de apoyo"}</p>{item.url && <a className="mt-2 inline-block text-sm font-semibold text-[#75A7FF] hover:text-white" href={item.url} target="_blank" rel="noreferrer">Abrir recurso</a>}</div>) : <p className="py-6 text-center text-sm text-[#8898AA]">No hay recursos registrados.</p>}</div>{isStaff && <Button className="mt-4 w-full" variant="outline" onClick={() => { const title = window.prompt("Título del recurso"); if (title) createResource.mutate({ subjectId: activeSubjectId, data: { title, description: null, resourceType: "reading", url: null } }); }}><Plus className="h-4 w-4" />Agregar recurso</Button>}</section></div>}
    {section === "ai" && isStaff && <section className="wij-card max-w-3xl p-5"><div className="flex gap-3"><div className="rounded-xl bg-[#7C3AED]/15 p-3 text-[#B59AFF]"><Bot className="h-6 w-6" /></div><div><h3 className="font-display text-lg font-bold text-white">Generador académico con IA</h3><p className="mt-1 text-sm text-[#8898AA]">Crea una propuesta con estructura, recursos y competencias antes de registrarla.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><input className="wij-input sm:col-span-1" value={topic} onChange={event => setTopic(event.target.value)} placeholder="Tema del curso" /><select className="wij-input" value={level} onChange={event => setLevel(event.target.value as typeof level)}><option value="basic">Básico</option><option value="intermediate">Intermedio</option><option value="advanced">Avanzado</option></select><input className="wij-input" value={period} onChange={event => setPeriod(event.target.value)} placeholder="Período" /></div><Button className="mt-4 bg-[#7C3AED] hover:bg-[#6D28D9]" disabled={!topic.trim() || generate.isPending} onClick={() => generate.mutate({ topic, level, period })}><Sparkles className="h-4 w-4" />{generate.isPending ? "Generando…" : "Generar propuesta"}</Button>{proposal && <div className="mt-5 rounded-xl border border-[#7C3AED]/30 bg-[#162040] p-4"><p className="font-display text-lg font-bold text-white">{proposal.code} · {proposal.name}</p><p className="mt-2 text-sm text-[#B8C4D6]">{proposal.description}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><div><p className="text-xs font-bold uppercase text-[#B59AFF]">Competencias</p><ul className="mt-2 space-y-2 text-sm text-[#B8C4D6]">{proposal.competencies?.map((item: any, index: number) => <li key={index}>• {item.title}</li>)}</ul></div><div><p className="text-xs font-bold uppercase text-[#B59AFF]">Recursos</p><ul className="mt-2 space-y-2 text-sm text-[#B8C4D6]">{proposal.resources?.map((item: any, index: number) => <li key={index}>• {item.title}</li>)}</ul></div></div></div>}</section>}
    {section === "messages" && <section className="wij-card p-5"><h3 className="font-display text-lg font-bold text-white">Mensajes de {subjectLabel?.name}</h3><div className="mt-4 max-h-72 space-y-3 overflow-y-auto">{messages.data?.length ? messages.data.map(item => <div key={item.id} className="rounded-xl border border-[#243356] bg-[#162040] p-3"><p className="text-sm text-[#E2E8F0]">{item.body}</p><p className="mt-1 text-xs text-[#8898AA]">{new Date(item.createdAt).toLocaleString()}</p></div>) : <p className="py-8 text-center text-sm text-[#8898AA]">Aún no hay mensajes en esta materia.</p>}</div><div className="mt-4 grid gap-3 sm:grid-cols-[220px_1fr_auto]"><select className="wij-input" value={recipientId} onChange={event => setRecipientId(event.target.value)}><option value="">Destinatario</option>{recipients.data?.map(person => <option key={person.id} value={person.id}>{person.name || person.email}</option>)}</select><input className="wij-input" value={message} onChange={event => setMessage(event.target.value)} placeholder="Escribe tu mensaje" /><Button disabled={!recipientId || !message.trim() || sendMessage.isPending} onClick={() => sendMessage.mutate({ subjectId: activeSubjectId, recipientId: Number(recipientId), body: message })}><Send className="h-4 w-4" />Enviar</Button></div></section>}
  </div>;
}
