import { BrainCircuit, CheckCircle2, CircleHelp, LoaderCircle, Send, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "./ui/button";

export default function ModuleAssessmentPanel({ moduleId, moduleTitle, isStaff, passedAssessmentIds }: { moduleId: number; moduleTitle: string; isStaff: boolean; passedAssessmentIds: number[] }) {
  const utils = trpc.useUtils();
  const assessments = trpc.academic.curriculum.assessments.useQuery({ moduleId });
  const generate = trpc.academic.curriculum.generateAssessment.useMutation({ onSuccess: async () => { await utils.academic.curriculum.assessments.invalidate({ moduleId }); toast.success("Evaluación generada y publicada."); }, onError: error => toast.error(error.message) });
  const submit = trpc.academic.curriculum.submitAssessment.useMutation({ onSuccess: async () => { await utils.academic.curriculum.progress.invalidate(); toast.success("Evaluación enviada. Revisa tu resultado."); }, onError: error => toast.error(error.message) });
  const assessment = assessments.data?.[0];
  const [answers, setAnswers] = useState<Record<string, number>>({});

  useEffect(() => { setAnswers({}); }, [assessment?.id]);

  if (isStaff) return <section className="mt-6 rounded-lg border border-[#C8AE72]/25 bg-[#343A33] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em] text-[#D8BF86]"><BrainCircuit className="h-4 w-4" />Evaluación de cierre</p><h5 className="mt-2 font-display text-lg font-bold text-white">Cuestionario del módulo</h5><p className="mt-1 max-w-xl text-sm leading-6 text-[#B8BBB2]">Genera una evaluación de cinco preguntas basada en las clases y objetivos de {moduleTitle}.</p></div><Button variant="outline" className="border-[#C8AE72]/40 text-[#E4D0A0] hover:bg-[#242724]" disabled={generate.isPending} onClick={() => generate.mutate({ moduleId })}><BrainCircuit className="h-4 w-4" />{generate.isPending ? "Generando…" : assessment ? "Generar otra evaluación" : "Generar evaluación con IA"}</Button></div>{assessment && <div className="mt-4 rounded-md border border-[#42463F] bg-[#1C201D] p-3"><p className="font-semibold text-white">{assessment.title}</p><p className="mt-1 text-sm text-[#B8BBB2]">{assessment.questions.length} preguntas · Puntaje mínimo: {assessment.passingScore}% · Publicada</p></div>}</section>;

  if (!assessment) return <section className="mt-6 rounded-lg border border-dashed border-[#42463F] bg-[#1C201D] p-5 text-sm text-[#B8BBB2]"><CircleHelp className="mb-2 h-5 w-5 text-[#D8BF86]" />La evaluación de cierre estará disponible cuando el docente la publique.</section>;

  const allAnswered = assessment.questions.every(question => answers[question.id] !== undefined);
  const result = submit.data;
  const alreadyPassed = passedAssessmentIds.includes(assessment.id);
  return <section className="mt-6 rounded-lg border border-[#C8AE72]/30 bg-[#343A33] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em] text-[#D8BF86]"><Trophy className="h-4 w-4" />Evaluación de cierre</p><h5 className="mt-2 font-display text-lg font-bold text-white">{assessment.title}</h5><p className="mt-1 text-sm leading-6 text-[#B8BBB2]">{assessment.description}</p></div>{alreadyPassed && <span className="inline-flex items-center gap-1 rounded-full border border-[#76C99C]/30 bg-[#76C99C]/10 px-3 py-1 text-xs font-bold text-[#A9E5BB]"><CheckCircle2 className="h-3.5 w-3.5" />Aprobada</span>}</div><div className="mt-5 space-y-5">{assessment.questions.map((question, index) => <fieldset key={question.id} className="rounded-md border border-[#42463F] bg-[#1C201D] p-4"><legend className="px-1 text-sm font-semibold text-white">{index + 1}. {question.prompt}</legend><div className="mt-3 grid gap-2">{question.options.map((option, optionIndex) => <label key={optionIndex} className={`flex cursor-pointer items-center gap-3 rounded-md border px-3 py-2.5 text-sm transition ${answers[question.id] === optionIndex ? "border-[#C8AE72]/60 bg-[#343A33] text-white" : "border-[#42463F] text-[#D8D9D2] hover:bg-[#242724]"}`}><input type="radio" name={`${assessment.id}-${question.id}`} className="accent-[#C8AE72]" checked={answers[question.id] === optionIndex} onChange={() => setAnswers(current => ({ ...current, [question.id]: optionIndex }))} />{option}</label>)}</div></fieldset>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-[#42463F] pt-4"><p className="text-xs text-[#B8BBB2]">Puntaje mínimo para aprobar: {assessment.passingScore}%.</p><Button disabled={!allAnswered || submit.isPending} onClick={() => submit.mutate({ assessmentId: assessment.id, answers: assessment.questions.map(question => ({ questionId: question.id, selectedOption: answers[question.id] })) })}>{submit.isPending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{submit.isPending ? "Calificando…" : "Enviar evaluación"}</Button></div>{result && <div className={`mt-5 rounded-md border p-4 ${result.passed ? "border-[#76C99C]/35 bg-[#76C99C]/10" : "border-[#C8AE72]/30 bg-[#343A33]"}`}><p className="font-display text-lg font-bold text-white">{result.passed ? "Evaluación aprobada" : "Resultado registrado"}</p><p className="mt-1 text-sm text-[#D8D9D2]">Obtuviste {result.score} de {result.maxScore} respuestas correctas ({result.percentage}%).</p><div className="mt-3 space-y-2">{result.review.map((item, index) => <p key={item.questionId} className="text-sm leading-6 text-[#B8BBB2]"><strong className="text-[#E4D0A0]">Pregunta {index + 1}:</strong> {item.explanation}</p>)}</div></div>}</section>;
}
